### ISSUE TITLE
mdlinks does not support two relative levels backwards

### ISSUE THREAD

**Issue by NoxInmortus** [artyom/mdlinks#1]
Hello,

I have this tree:
```
--main/docs/subfolder/readme.md
--main/docs/file1.md
--main/file2.md
```

In readme.md I have : 
```plaintext
[test](../file1.md) and [test2](../../file2.md)
```

mdlinks reports:
```
main/docs/subfolder/readme.md: link "../../file2.md" points to a non-existing file
```

**Comment by artyom** [comment]
@NoxInmortus can you please post an output of `find . -type f` command, executed in the same directory as you run mdlinks?

I cannot reproduce this bug using the layout you described:

```
bug1 ¶ mkdir -p -- --main/docs/subfolder/
bug1 ¶ cat <<EOF > --main/docs/subfolder/readme.md
heredoc> [test](../file1.md) and [test2](../../file2.md)
heredoc> EOF
bug1 ¶ touch -- --main/docs/file1.md --main/file2.md
bug1 ¶ find . -type f
./--main/docs/file1.md
./--main/docs/subfolder/readme.md
./--main/file2.md
bug1 ¶ mdlinks .
bug1 ¶ echo $?
0
```

**Comment by NoxInmortus** [comment]
I think I understand the logic, I was running mdlinks in the docs folder rather than in the main folder, in this case it will not find `file2.md`, as the same logic apply for find

**Comment by artyom** [comment]
That's correct! It won't go above the directory provided with the `-dir` flag, which defaults to the current directory.
The use case is optimised to run this at the root of the document tree, that eventually would be rendered/presented as a standalone collection of pages (a website).

**Comment by NoxInmortus** [comment]
thanks for the clarification, all is in order then.

and thanks for the work on mdlinks
